import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  English: {},
  Deutsch: {
    "Home": "Startseite",
    "Solutions": "Lösungen",
    "Start Your E-com Now": "Jetzt E-Com starten",
    "Start Fulfillment": "Fulfillment starten",
    "Select Language": "Sprache auswählen",
    "Contact Architecture": "Kontakt Architektur",
    
    // Hero
    "THE SWISS LOGISTICS EDGE": "DER SCHWEIZER LOGISTIK-VORSPRUNG",
    "PARCELLINO": "PARCELLINO",
    "PRECISION": "PRÄZISION",
    "FULFILLMENT": "FULFILLMENT",
    "From the heart of Switzerland to every corner of the nation. Real-time logistics, multi-language integration, and the Swiss standard of reliability.": "Vom Herzen der Schweiz in jeden Winkel des Landes. Echtzeit-Logistik, mehrsprachige Integration und der Schweizer Standard für Zuverlässigkeit.",
    "See our solutions": "Unsere Lösungen ansehen",
    "View Network": "Netzwerk anzeigen",
    "System Status": "Systemstatus",
    "26 Cantons": "26 Kantone",
    "100% NATIONWIDE COVERAGE": "100% SCHWEIZWEITE ABDECKUNG",
    "Seamless local fulfillment from Zurich to Geneva.": "Nahtloses lokales Fulfillment von Zürich bis Genf.",
    "Scroll to explore": "Zum Erkunden scrollen",

    // BordersSection
    "Swiss coverage is": "Die Schweizweite Abdeckung ist",
    "absolute": "vollständig",
    "Nationwide": "im ganzen Land",
    "Our infrastructure is optimized exclusively for the Swiss landscape. From Geneva to Zurich, Lugano to Basel, we provide flawless fulfillment tailored perfectly to Switzerland's unique multi-language cantons.": "Unsere Infrastruktur ist exklusiv für die Schweizer Landschaft optimiert. Von Genf bis Zürich, von Lugano bis Basel bieten wir ein makelloses Fulfillment, das perfekt auf die einzigartigen mehrsprachigen Kantone der Schweiz zugeschnitten ist.",
    "SWISS MULTI-LANGUAGE ARCHITECTURE": "SCHWEIZER MEHRSPRACHIGE ARCHITEKTUR",

    // BentoGrid
    "ENGINEERED EXCELLENCE": "KONSTRUIERTE EXZELLENZ",
    "ECOSYSTEM OF PRECISION": "ÖKOSYSTEM DER PRÄZISION",
    "E-Com Integration": "E-Com-Integration",
    "One-click Shopify/Woo/Amazon sync. Our system ensures your stock levels are never out of sync.": "Ein-Klick Shopify/Woo/Amazon-Synchronisation. Unser System stellt sicher, dass Ihre Lagerbestände nie asynchron sind.",
    "Explore Tech": "Technik entdecken",
    "Sustainable Packaging": "Nachhaltige Verpackung",
    "The future of eco-conscious delivery. 100% biodegradable materials engineered for structural integrity and premium unboxing experiences.": "Die Zukunft der umweltbewussten Lieferung. 100% biologisch abbaubare Materialien, entwickelt für strukturelle Integrität und erstklassige Unboxing-Erlebnisse.",
    "View Eco-Policy": "Öko-Richtlinie ansehen",
    "Rapid Fulfillment": "Schnelles Fulfillment",
    "Order-to-shipping in 60 minutes. Meticulous picking flows engineered for maximum efficiency.": "Von der Bestellung bis zum Versand in 60 Minuten. Sorgfältige Kommissionierabläufe, die auf maximale Effizienz ausgelegt sind.",
    "Returns Management": "Retouren-Management",
    "Automated verification and instant restocking for peak efficiency.": "Automatisierte Überprüfung und sofortige Wiedereinlagerung für höchste Effizienz.",

    // MetricsSection
    "MISSION-CRITICAL SUPPORT": "MISSION-CRITICAL SUPPORT",
    "ORDER ACCURACY RATE": "BESTELLGENAUIGKEIT",
    "STRATEGIC REACH": "STRATEGISCHE REICHWEITE",

    // Solutions Page
    "Solutions Architecture": "Lösungsarchitektur",
    "Tailored Logistics for": "Maßgeschneiderte Logistik für",
    "Swiss Ambition.": "Schweizer Ambitionen.",
    "Swiss-engineered precision for industries that demand perfection.": "Schweizer Präzision für Branchen, die Perfektion fordern.",
    "Powering Swiss Trade Leaders": "Antrieb für Schweizer Handelsführer",
    "E-Commerce Fulfillment": "E-Commerce-Fulfillment",
    "Seamlessly scale your D2C brand with high-volume, precision-driven order processing. From pick & pack to last-mile — we architect speed.": "Skalieren Sie Ihre D2C-Marke nahtlos mit hochvolumigem, präzisionsgesteuertem Fulfillment. Von Pick & Pack bis zur letzten Meile - wir entwerfen Geschwindigkeit.",
    "Explore this solution": "Diese Lösung erkunden",
    "Luxury Goods Handling": "Umgang mit Luxusgütern",
    "White-glove treatment with enhanced security, premium unboxing experiences, and meticulous care for your most valuable inventory.": "White-Glove-Behandlung mit erhöhter Sicherheit, erstklassigen Unboxing-Erlebnissen und akribischer Sorgfalt für Ihr wertvollstes Inventar.",
    "Medical & High-Value": "Medizin & Hoher Wert",
    "Temperature-controlled environments and strict compliance protocols for sensitive inventories that demand zero-tolerance accuracy.": "Temperaturkontrollierte Umgebungen und strenge Compliance-Protokolle für sensible Bestände, die eine Null-Toleranz-Genauigkeit erfordern.",
    "Returns Management (Desc)": "Automatisierte Qualitätsprüfungen und schnelle Wiedereinlagerung zum Schutz Ihres Gewinns. Verwandeln Sie Retouren in einbehaltene Einnahmen und erneuertes Vertrauen.",
    "Swiss Cantonal Logistics": "Schweizer Kantonslogistik",
    "Flawless delivery across all 26 cantons with optimized route networks and localized language handling. We cover Switzerland perfectly so you can focus on local growth.": "Reibungslose Lieferung in alle 26 Kantone mit optimierten Routennetzwerken und lokalisierter Sprachregelung. Wir decken die Schweiz perfekt ab, damit Sie sich auf lokales Wachstum konzentrieren können.",
    "Deep Architecture — ": "Tiefe Architektur — ",
    "Expert Insight": "Experteneinblick",
    "Core Capabilities": "Kernkompetenzen",
    "Ready to discuss this architecture for your brand?": "Sind Sie bereit, diese Architektur für Ihre Marke zu besprechen?",
    "Schedule Technical Brief": "Technisches Briefing planen",
    "The Parcellino Advantage": "Der Parcellino-Vorteil",
    "Swiss Precision": "Schweizer Präzision",
    "99.9% fulfillment accuracy across all sectors.": "99,9% Fulfillment-Genauigkeit über alle Sektoren hinweg.",
    "Swiss-wide Coverage": "Schweizweite Abdeckung",
    "Direct lanes to all 26 cantons.": "Direkte Linien in alle 26 Kantone.",
    "Eco-Friendly / Swiss Made": "Umweltfreundlich / Swiss Made",
    "\"Sustainable Packaging & Carbon-Balanced Logistics\"": "\"Nachhaltige Verpackung & klimaneutrale Logistik\"",
    "We engineer customized, eco-friendly unboxing experiences that align with your brand values while mitigating environmental impact through optimized shipping routes and climate-neutral partners.": "Wir entwickeln maßgeschneiderte, umweltfreundliche Unboxing-Erlebnisse, die mit Ihren Markenwerten übereinstimmen und gleichzeitig die Umweltauswirkungen durch optimierte Versandrouten und klimaneutrale Partner mindern.",
    "Request Strategy": "Strategie anfordern",
    "Common Inquiries": "Häufige Anfragen",
    "Frequently Asked Questions": "Häufig gestellte Fragen",
    "What is your typical turnaround for e-commerce integration?": "Wie ist Ihre typische Bearbeitungszeit für E-Commerce-Integrationen?",
    "Most major platforms (Shopify, WooCommerce, Amazon) can be integrated within 24-48 hours. Our technical team provides end-to-end support for custom API setups.": "Die meisten großen Plattformen (Shopify, WooCommerce, Amazon) können innerhalb von 24-48 Stunden integriert werden. Unser technisches Team bietet End-to-End-Support für benutzerdefinierte API-Setups.",
    "Do you deliver to alpine and remote Swiss regions?": "Liefern Sie auch in alpine und abgelegene Schweizer Regionen?",
    "Yes. We deliver to every single valley and mountain village across all 26 cantons with our specialized Swiss logistics partners, guaranteeing on-time arrival.": "Ja. Wir liefern in jedes einzelne Tal und Bergdorf in allen 26 Kantonen mit unseren spezialisierten Schweizer Logistikpartnern und garantieren eine pünktliche Ankunft.",
    "Are your packaging materials eco-friendly?": "Sind Ihre Verpackungsmaterialien umweltfreundlich?",
    "Yes. We use 100% biodegradable, climate-neutral materials engineered specifically for safe, premium, and sustainable unboxing experiences across Switzerland.": "Ja. Wir verwenden zu 100% biologisch abbaubare, klimaneutrale Materialien, die speziell für sichere, erstklassige und nachhaltige Unboxing-Erlebnisse in der gesamten Schweiz entwickelt wurden.",
    "How does your returns management process work?": "Wie funktioniert Ihr Retouren-Management-Prozess?",
    "Our automated returns portal allows customers to initiate returns easily. Once received, we perform rapid quality checks and restock or process according to your brand's specific protocols.": "Unser automatisiertes Retourenportal ermöglicht es Kunden, Retouren einfach zu veranlassen. Sobald sie eingegangen sind, führen wir schnelle Qualitätsprüfungen durch und lagern sie gemäß den spezifischen Protokollen Ihrer Marke ein oder verarbeiten sie weiter.",

    // Testimonials
    "SWISS LEADERSHIP": "SCHWEIZER FÜHRUNG",
    "Logistics is the": "Die Logistik ist der",
    "heartbeat": "Herzschlag",
    "of your brand. We make sure it never skips a beat.": "Ihrer Marke. Wir sorgen dafür, dass er nie aussetzt.",
    "Founder & CEO": "Gründerin & CEO",
    "VOICES OF PARTNERSHIP": "STIMMEN DER PARTNERSCHAFT",
    "THEY TRUST PARCELLINO.": "SIE VERTRAUEN PARCELLINO.",
    "Since migrating to Parcellino, our order-to-door time in DACH dropped by 40%. Their fulfillment precision is nothing short of Swiss.": "Seit der Umstellung auf Parcellino hat sich unsere Order-to-Door-Zeit in der DACH-Region um 40% verkürzt. Ihre Fulfillment-Präzision ist einfach schweizerisch.",
    "Operations Director, Velox Wear": "Betriebsleiter, Velox Wear",
    "We needed a partner who treats luxury goods with respect. Parcellino’s white-glove service transformed our customer unboxing experience.": "Wir brauchten einen Partner, der Luxusgüter mit Respekt behandelt. Der White-Glove-Service von Parcellino hat das Unboxing-Erlebnis unserer Kunden verändert.",
    "Founder, Lumina Swiss": "Gründer, Lumina Swiss",
    
    // CTA Section
    "Ready to Scale Your Logistics?": "Bereit, Ihre Logistik zu skalieren?",
    "Connect with our solutions architects for a tailored technical brief and Swiss scaling strategy.": "Kontaktieren Sie unsere Lösungsarchitekten für ein maßgeschneidertes technisches Briefing und eine Schweizer Skalierungsstrategie.",
    "Book a Strategy Call": "Strategiegespräch buchen",
    "Speak to an Expert Now": "Jetzt mit einem Experten sprechen",
    "SCALABILITY": "SKALIERBARKEIT",
    "READY TO UPGRADE": "BEREIT FÜR EIN UPGRADE",
    "YOUR ARCHITECTURE?": "IHRER ARCHITEKTUR?",
    "Join leading D2C brands leveraging Swiss precision for nationwide growth.": "Schließen Sie sich führenden D2C-Marken an, die Schweizer Präzision für nationales Wachstum nutzen.",
    "Initiate Integration": "Integration starten",
    "Or contact our engineering team": "Oder kontaktieren Sie unser Technik-Team",

    // Footer
    "Switzerland's premier fulfillment architecture. Precision, speed, and neutrality for local commerce.": "Die führende Fulfillment-Architektur der Schweiz. Präzision, Geschwindigkeit und Neutralität für den lokalen Handel.",
    "Zürich, Switzerland": "Zürich, Schweiz",
    "Operations": "Betrieb",
    "E-Com Sync": "E-Com-Synchronisation",
    "Luxury Handing": "Luxus-Handling",
    "Returns AI": "Retouren-KI",
    "Customs API": "Zoll-API",
    "Architecture": "Architektur",
    "Network Map": "Netzwerkkarte",
    "Security": "Sicherheit",
    "Data Privacy": "Datenschutz",
    "Sustainability": "Nachhaltigkeit",
    "Contact": "Kontakt",
    "Partner Portal": "Partner-Portal",
    "Support": "Support",
    "© 2026 Parcellino Swiss. Engineered in Zurich.": "© 2026 Parcellino Swiss. Entwickelt in Zürich.",
    "Terms": "Bedingungen",
    "Privacy": "Datenschutz",

    // Solutions Details text
    "Our warehouse automation reduces pick-error rates to less than 0.01%, ensuring your customers receive exactly what they ordered, every time.": "Unsere Lagerautomatisierung reduziert die Fehlerquote beim Kommissionieren auf weniger als 0,01% und stellt sicher, dass Ihre Kunden jedes Mal genau das erhalten, was sie bestellt haben.",
    "Real-time Inventory Sync": "Echtzeit-Bestandssynchronisation",
    "Same-day Dispatch (14:00 cutoff)": "Versand am selben Tag (14:00 Uhr Cutoff)",
    "Custom Brand Packaging": "Individuelle Markenverpackung",
    "Fragile Item Specialists": "Spezialisten für zerbrechliche Artikel",
    "Luxury requires a different standard of care. We treat every parcel as a masterpiece, with dedicated white-glove inspection zones.": "Luxus erfordert einen anderen Sorgfaltsstandard. Wir behandeln jedes Paket als Meisterwerk, mit speziellen White-Glove-Inspektionszonen.",
    "Enhanced Security Vaults": "Erweiterte Sicherheitstresore",
    "Climate Controlled Storage": "Klimatisierte Lagerung",
    "Premium Tissue & Wax Seal handling": "Umgang mit Premium-Seidenpapier & Wachssiegeln",
    "Serial Number Tracking": "Seriennummern-Tracking",
    "Precision is non-negotiable in medical logistics. Our facility meets the highest Swiss standards for pharmaceutical storage.": "Präzision ist in der Medizinlogistik nicht verhandelbar. Unsere Anlage erfüllt die höchsten Schweizer Standards für die pharmazeutische Lagerung.",
    "GDP Compliant Handling": "GDP-konformes Handling",
    "Cold Chain Logistics": "Kühlkettenlogistik",
    "Batch & Expiry Management": "Chargen- & Verfall-Management",
    "Sterile Environment Options": "Optionen für sterile Umgebungen",
    "Returns are the second point of customer contact. We process returns in under 24 hours to ensure rapid restocking or liquidation.": "Retouren sind der zweite Kundenkontaktpunkt. Wir bearbeiten Retouren in weniger als 24 Stunden, um eine schnelle Wiedereinlagerung oder Liquidation sicherzustellen.",
    "Photo-Verified Inspections": "Fotoverifizierte Inspektionen",
    "Quality Grading System": "Qualitätseinstufungssystem",
    "Rapid Customer Refunds": "Schnelle Kundenrückerstattungen",
    "Regional Consolidation": "Regionale Konsolidierung",
    "Cross-border trade shouldn't be a bottleneck. Our in-house customs experts ensure 100% compliance with EU and Swiss regulations.": "Grenzüberschreitender Handel sollte kein Engpass sein. Unsere internen Zollexperten gewährleisten 100%ige Konformität mit EU- und Schweizer Vorschriften.",
    "IOSS & OSS Management": "IOSS- & OSS-Management",
    "HS Code Classification": "HS-Code-Klassifizierung",
    "Duty & Tax Calculation": "Zoll- & Steuerberechnung",
    "Frictionless EU-Swiss corridor": "Reibungsloser EU-Schweiz-Korridor",
    
    // NEW ADDITIONS / MISSING TRANSLATIONS
    "E-Com Management": "E-Com-Management",
    "Engineered efficiency.": "Konstruierte Effizienz.",
    "Meticulous storage in our single, highly secure Swiss facility. Optimized storage space custom-tailored for early-stage brands.": "Sorgfältige Lagerung in unserer zentralen, hochsicheren Schweizer Einrichtung. Optimierter Lagerplatz, maßgeschneidert für aufstrebende Marken.",
    "See How We Work": "Unsere Arbeitsweise ansehen",
    "See Process": "Prozess ansehen",
    "Swiss Warehousing": "Schweizer Lagerhaltung",
    "View Storage": "Lagerung ansehen",
    "We manually handle and process your Shopify, WooCommerce, and Amazon orders with Swiss precision. Perfect for emerging brands looking for error-free execution and personal care without complex setups.": "Wir bearbeiten und wickeln Ihre Shopify-, WooCommerce- und Amazon-Bestellungen manuell mit Schweizer Präzision ab. Perfekt für aufstrebende Marken, die fehlerfreie Ausführung und persönliche Betreuung ohne komplexe Setups suchen.",
    "© 2026 Precision Fulfillment": "© 2026 Präzisions-Fulfillment",
    "We deliver more than products. We provide trust, efficiency and growth.": "Wir liefern mehr als Produkte. Wir liefern Vertrauen, Effizienz und Wachstum.",
    "100% Biodegradable Boxes": "100% biologisch abbaubare Kartons",
    "60-Minute Picking Window": "60-Minuten-Kommissionierungsfenster",
    "Carbon-Balanced Operations": "Klimaneutrale Betriebsabläufe",
    "Climate-Controlled Space": "Klimatisierte Flächen",
    "Condition Grading Audit": "Zustandsbewertungs-Audit",
    "Custom Tailored Shelving": "Maßgeschneiderte Regalsysteme",
    "Deliver unforgettable premium unboxing moments with high-grade, sustainable materials certified for maximum shipping protection.": "Liefern Sie unvergessliche Premium-Unboxing-Momente mit hochwertigen, nachhaltigen Materialien, die für maximalen Versandschutz zertifiziert sind.",
    "Eco-Certified Fillers": "Öko-zertifizierte Füllstoffe",
    "Ensure immediate product validation and rapid restocking to maintain inventory liquidity and customer satisfaction.": "Gewährleisten Sie eine sofortige Produktvalidierung und schnelle Wiederauffüllung, um die Liquidität des Lagerbestands und die Kundenzufriedenheit aufrechtzuerhalten.",
    "Express Dispatch Services": "Express-Versanddienste",
    "High-Priority Scheduling": "Priorisierte Disposition",
    "High-Security Protocols": "Hochsicherheitsprotokolle",
    "Instant Return Restocking": "Sofortige Wiedereinlagerung von Retouren",
    "Manual Quality Audit": "Manuelles Qualitätsaudit",
    "Our swift picking processes move with synchronized precision, minimizing transit delays and expediting shipping times.": "Unsere schnellen Kommissionierungsprozesse arbeiten mit synchronisierter Präzision, minimieren Transitverzögerungen und beschleunigen die Versandzeiten.",
    "Personalized Client Dashboard": "Personalisiertes Kunden-Dashboard",
    "Premium Custom Branding": "Premium-Kundenbranding",
    "Shopify & WooCommerce Integration": "Shopify- & WooCommerce-Integration",
    "Single Secure Swiss Facility": "Zentrale sichere Schweizer Einrichtung",
    "Swift Customer Status Updates": "Schnelle Kundenstatus-Updates",
    "Verification & Inspection": "Verifizierung & Inspektion",
    "We process orders with absolute white-glove manual precision, ensuring 100% accuracy and customized attention for emerging brands.": "Wir bearbeiten Bestellungen mit absoluter White-Glove-Präzision und garantieren 100% Genauigkeit und individuelle Aufmerksamkeit für aufstrebende Marken.",
    "Your inventory is protected within our single state-of-the-art secure Swiss facility with optimized shelving and strict climate control.": "Ihr Inventar ist in unserer hochmodernen, sicheren Schweizer Einrichtung mit optimierten Regalen und strenger Klimatisierung geschützt.",
    "Zero Pick-Error Tolerance": "Null-Fehler-Kommissionierungstoleranz",
    "Zero-Setup Complexities": "Keine Einrichtungs-Komplexitäten",
    "Swiss Ambition": "Schweizer Ambitionen",
    "Our company was established by a ": "Unser Unternehmen wurde von einer ",
    "woman entrepreneur": "Unternehmerin",
    " who has seen and felt the pain in the fulfillment process, and we have a ": " gegründet, die den Schmerz im Fulfillment-Prozess selbst erlebt hat, und wir verfolgen eine ",
    "simple vision": "einfache Vision",
    " to make fulfillment ": ", um das Fulfillment ",
    "seamless, reliable and exceptional": "reibungslos, zuverlässig und außergewöhnlich zu gestalten",
    "Smart logistics, proactive service and uncompromising attention to detail": "Intelligente Logistik, proaktiver Service und kompromisslose Liebe zum Detail",
    ", all for the purpose of ensuring that the quality of our service is reflected in every order you place.": ", all dies mit dem Ziel, dass sich die Qualität unseres Service in jeder Ihrer Bestellungen widerspiegelt.",
    "We deliver more than products.": "Wir liefern mehr als Produkte.",
    "We provide trust, efficiency and growth.": "Wir liefern Vertrauen, Effizienz und Wachstum.",
    "WhatsApp": "WhatsApp",
    "Pioneering Swiss fulfillment and E-commerce logistics Switzerland solutions. From the heart of the nation, we provide real-time logistics and the Swiss standard of reliability.": "Wegweisende Lösungen für Swiss Fulfillment und E-Commerce-Logistik Schweiz. Aus dem Herzen der Nation bieten wir Echtzeit-Logistik und den Schweizer Standard an Zuverlässigkeit.",
    "Premier Shopify fulfillment Switzerland services. We manually handle and process your Shopify, WooCommerce, and Amazon orders with Swiss precision, offering error-free care without complexities.": "Erstklassige Shopify Fulfillment Switzerland Services. Wir wickeln Ihre Shopify-, WooCommerce- und Amazon-Bestellungen manuell mit Schweizer Präzision ab und bieten fehlerfreie Betreuung ohne Komplexität.",
    "Leading provider of fulfillment Switzerland services and precision architecture.": "Führender Anbieter von Fulfillment Switzerland Services und Präzisionsarchitektur.",
    "Client Success": "Kundenerfolg",
    "Trusted by Industry Leaders": "Vertrauen von Branchenführern",
    "We have been working with Parcellino in IT/logistics for our brand Hydrux for some time now... The cooperation is efficient, reliable, and absolutely professional.": "Wir arbeiten nun schon seit einiger Zeit mit Parcellino in der IT/Logistik für unsere Marke Hydrux zusammen... Die Zusammenarbeit ist effizient, zuverlässig und absolut professionell.",
    "Parcellino takes over our fulfillment and we at dirts benefit from the fast processing... Parcellino is the perfect partner.": "Parcellino übernimmt unser Fulfillment und wir bei dirts profitieren von der schnellen Abwicklung... Parcellino ist der perfekte Partner.",
    "By outsourcing our warehouse and fulfillment, we benefited on our core competencies while being sure this part is handled professionally.": "Durch die Auslagerung unseres Lagers und Fulfillments konnten wir uns auf unsere Kernkompetenzen konzentrieren und gleichzeitig sicher sein, dass dieser Teil professionell abgewickelt wird.",
    "Founder": "Gründer",
    "Swiss Precision Warehouse": "Schweizer Präzisionslager",
    "Swiss Logistics Network": "Schweizer Logistiknetzwerk",
    "Toggle Theme": "Design umschalten"
  },
  Français: {
    "Home": "Accueil",
    "Solutions": "Solutions",
    "Start Your E-com Now": "Lancez votre E-com",
    "Start Fulfillment": "Démarrer le Fulfillment",
    "Select Language": "Sélectionner la langue",
    "Contact Architecture": "Architecture de Contact",
    "THE SWISS LOGISTICS EDGE": "L'AVANTAGE LOGISTIQUE SUISSE",
    "PARCELLINO": "PARCELLINO",
    "PRECISION": "PRÉCISION",
    "FULFILLMENT": "FULFILLMENT",
    "From the heart of Switzerland to every corner of the nation. Real-time logistics, multi-language integration, and the Swiss standard of reliability.": "Du cœur de la Suisse à chaque coin du pays. Logistique en temps réel, intégration multilingue et norme de fiabilité suisse.",
    "See our solutions": "Voir nos solutions",
    "View Network": "Voir le Réseau",
    "System Status": "État du Système",
    "26 Cantons": "26 Cantons",
    "100% NATIONWIDE COVERAGE": "COUVERTURE NATIONALE À 100%",
    "Seamless local fulfillment from Zurich to Geneva.": "Fulfillment local fluide de Zurich à Genève.",
    "Scroll to explore": "Faire défiler pour explorer",
    "Swiss coverage is": "La couverture suisse est",
    "absolute": "absolue",
    "Our infrastructure is optimized exclusively for the Swiss landscape. From Geneva to Zurich, Lugano to Basel, we provide flawless fulfillment tailored perfectly to Switzerland's unique multi-language cantons.": "Notre infrastructure est optimisée exclusivement pour le paysage suisse. De Genève à Zurich, de Lugano à Bâle, nous fournissons un fulfillment impeccable, parfaitement adapté aux cantons multilingues uniques de la Suisse.",
    "SWISS MULTI-LANGUAGE ARCHITECTURE": "ARCHITECTURE MULTILINGUE SUISSE",
    "ENGINEERED EXCELLENCE": "L'EXCELLENCE CONÇUE",
    "ECOSYSTEM OF PRECISION": "ÉCOSYSTÈME DE PRÉCISION",
    "E-Com Integration": "Intégration E-Com",
    "One-click Shopify/Woo/Amazon sync. Our system ensures your stock levels are never out of sync.": "Synchronisation en un clic Shopify/Woo/Amazon. Notre système garantit que vos niveaux de stock ne sont jamais désynchronisés.",
    "Explore Tech": "Explorer la Technologie",
    "Sustainable Packaging": "Emballage Durable",
    "The future of eco-conscious delivery. 100% biodegradable materials engineered for structural integrity and premium unboxing experiences.": "L'avenir de la livraison éco-responsable. Matériaux 100% biodégradables conçus pour l'intégrité structurelle et des expériences de déballage haut de gamme.",
    "View Eco-Policy": "Voir la Politique Écologique",
    "Rapid Fulfillment": "Fulfillment Rapide",
    "Order-to-shipping in 60 minutes. Meticulous picking flows engineered for maximum efficiency.": "De la commande à l'expédition en 60 minutes. Des flux de préparation méticuleux conçus pour une efficacité maximale.",
    "Returns Management": "Returns Management",
    "Automated verification and instant restocking for peak efficiency.": "Vérification automatisée et réassort instantané pour une efficacité maximale.",
    "MISSION-CRITICAL SUPPORT": "SUPPORT CRITIQUE",
    "ORDER ACCURACY RATE": "TAUX DE PRÉCISION DES COMMANDES",
    "STRATEGIC REACH": "PORTÉE STRATÉGIQUE",
    "Solutions Architecture": "Architecture des Solutions",
    "Tailored Logistics for": "Logistique Sur Mesure pour",
    "Swiss Ambition.": "L'Ambition Suisse.",
    "Swiss-engineered precision for industries that demand perfection.": "La précision suisse pour les industries exigeant la perfection.",
    "Powering Swiss Trade Leaders": "Propulser les Leaders du Commerce Suisse",
    "E-Commerce Fulfillment": "Fulfillment E-Commerce",
    "Seamlessly scale your D2C brand with high-volume, precision-driven order processing. From pick & pack to last-mile — we architect speed.": "Développez harmonieusement votre marque D2C grâce à un traitement de commandes à haut volume, axé sur la précision. Du prélèvement et de l'emballage jusqu'au dernier kilomètre, nous concevons la rapidité.",
    "Explore this solution": "Explorer cette solution",
    "Luxury Goods Handling": "Manutention de Produits de Luxe",
    "White-glove treatment with enhanced security, premium unboxing experiences, and meticulous care for your most valuable inventory.": "Traitement haut de gamme avec une sécurité renforcée, des expériences de déballage premium et un soin méticuleux pour votre inventaire le plus précieux.",
    "Medical & High-Value": "Médical & Haute Valeur",
    "Temperature-controlled environments and strict compliance protocols for sensitive inventories that demand zero-tolerance accuracy.": "Environnements à température contrôlée et protocoles de conformité stricts pour les stocks sensibles exigeant une précision à tolérance zéro.",
    "Returns Management (Desc)": "Inspections de qualité automatisées et réassort rapide pour protéger vos marges. Transformez les retours en revenus conservés et en confiance renouvelée.",
    "Swiss Cantonal Logistics": "Logistique Cantonale Suisse",
    "Flawless delivery across all 26 cantons with optimized route networks and localized language handling. We cover Switzerland perfectly so you can focus on local growth.": "Livraison impeccable dans les 26 cantons grâce à des réseaux d'itinéraires optimisés et une gestion linguistique localisée. Nous couvrons parfaitement la Suisse pour que vous puissiez vous concentrer sur votre croissance locale.",
    "Deep Architecture — ": "Architecture Profonde — ",
    "Expert Insight": "L'Avis d'un Expert",
    "Core Capabilities": "Capacités Principales",
    "Ready to discuss this architecture for your brand?": "Prêt à discuter de cette architecture pour votre marque ?",
    "Schedule Technical Brief": "Planifier un Briefing Technique",
    "The Parcellino Advantage": "L'Avantage Parcellino",
    "Swiss Precision": "Précision Suisse",
    "99.9% fulfillment accuracy across all sectors.": "Précision de fulfillment de 99,9 % dans tous les secteurs.",
    "Swiss-wide Coverage": "Couverture Nationale",
    "Direct lanes to all 26 cantons.": "Liaisons directes vers les 26 cantons.",
    "Eco-Friendly / Swiss Made": "Écologique / Fabrication Suisse",
    "\"Sustainable Packaging & Carbon-Balanced Logistics\"": "\"Emballage Durable & Logistique Neutre en Carbone\"",
    "We engineer customized, eco-friendly unboxing experiences that align with your brand values while mitigating environmental impact through optimized shipping routes and climate-neutral partners.": "Nous concevons des expériences de déballage personnalisées et écologiques qui correspondent aux valeurs de votre marque, tout en réduisant l'impact environnemental grâce à des itinéraires optimisés et des partenaires neutres en carbone.",
    "Request Strategy": "Demander une Stratégie",
    "Common Inquiries": "Questions Fréquentes",
    "Frequently Asked Questions": "Foire aux Questions",
    "What is your typical turnaround for e-commerce integration?": "Quel est votre délai typique pour l'intégration e-commerce ?",
    "Most major platforms (Shopify, WooCommerce, Amazon) can be integrated within 24-48 hours. Our technical team provides end-to-end support for custom API setups.": "La plupart des grandes plateformes (Shopify, WooCommerce, Amazon) peuvent être intégrées en 24 à 48 heures. Notre équipe technique fournit un support complet pour les configurations d'API personnalisées.",
    "Do you deliver to alpine and remote Swiss regions?": "Livrez-vous dans les régions alpines et reculées de Suisse ?",
    "Yes. We deliver to every single valley and mountain village across all 26 cantons with our specialized Swiss logistics partners, guaranteeing on-time arrival.": "Oui. Nous livrons dans chaque vallée et village de montagne des 26 cantons avec nos partenaires logistiques suisses spécialisés, en garantissant une arrivée à temps.",
    "Are your packaging materials eco-friendly?": "Vos matériaux d'emballage sont-ils écologiques ?",
    "Yes. We use 100% biodegradable, climate-neutral materials engineered specifically for safe, premium, and sustainable unboxing experiences across Switzerland.": "Oui. Nous utilisons des matériaux 100 % biodégradables et climatiquement neutres, conçus spécifiquement pour des expériences de déballage sûres, premium et durables dans toute la Suisse.",
    "How does your returns management process work?": "Comment fonctionne votre processus de returns management ?",
    "Our automated returns portal allows customers to initiate returns easily. Once received, we perform rapid quality checks and restock or process according to your brand's specific protocols.": "Notre portail de retours automatisé permet aux clients d'initier des retours facilement. Une fois reçus, nous effectuons des contrôles de qualité rapides et réapprovisionnons ou traitons selon les protocoles spécifiques de votre marque.",
    "SWISS LEADERSHIP": "LEADERSHIP SUISSE",
    "Logistics is the": "La logistique est le",
    "heartbeat": "battement de cœur",
    "of your brand. We make sure it never skips a beat.": "de votre marque. Nous veillons à ce qu'elle ne manque jamais un battement.",
    "Founder & CEO": "Fondatrice & PDG",
    "VOICES OF PARTNERSHIP": "VOIX DE PARTENARIAT",
    "THEY TRUST PARCELLINO.": "ILS FONT CONFIANCE À PARCELLINO.",
    "Since migrating to Parcellino, our order-to-door time in DACH dropped by 40%. Their fulfillment precision is nothing short of Swiss.": "Depuis notre migration vers Parcellino, notre délai de commande à la porte dans la région DACH a chuté de 40 %. Leur précision de fulfillment est tout simplement suisse.",
    "Operations Director, Velox Wear": "Directeur des Opérations, Velox Wear",
    "We needed a partner who treats luxury goods with respect. Parcellino’s white-glove service transformed our customer unboxing experience.": "Nous avions besoin d'un partenaire qui traite les produits de luxe avec respect. Le service haut de gamme de Parcellino a transformé l'expérience de déballage de nos clients.",
    "Founder, Lumina Swiss": "Fondateur, Lumina Swiss",
    "Ready to Scale Your Logistics?": "Prêt à Mettre à l'Échelle votre Logistique ?",
    "Connect with our solutions architects for a tailored technical brief and Swiss scaling strategy.": "Contactez nos architectes de solutions pour un briefing technique sur mesure et une stratégie de croissance suisse.",
    "Book a Strategy Call": "Réserver un Appel Stratégique",
    "Speak to an Expert Now": "Parler à un Expert Maintenant",
    "SCALABILITY": "ÉVOLUTIVITÉ",
    "READY TO UPGRADE": "PRÊT À AMÉLIORER",
    "YOUR ARCHITECTURE?": "VOTRE ARCHITECTURE ?",
    "Join leading D2C brands leveraging Swiss precision for nationwide growth.": "Rejoignez les grandes marques D2C qui exploitent la précision suisse pour leur croissance nationale.",
    "Initiate Integration": "Initier l'Intégration",
    "Or contact our engineering team": "Ou contactez notre équipe d'ingénieurs",
    "Switzerland's premier fulfillment architecture. Precision, speed, and neutrality for local commerce.": "La première architecture de fulfillment de Suisse. Précision, vitesse et neutralité pour le commerce local.",
    "Zürich, Switzerland": "Zurich, Suisse",
    "Operations": "Opérations",
    "E-Com Sync": "Synchro E-Com",
    "Luxury Handing": "Manutention de Luxe",
    "Returns AI": "IA de Retours",
    "Customs API": "API Douanière",
    "Architecture": "Architecture",
    "Network Map": "Carte du Réseau",
    "Security": "Sécurité",
    "Data Privacy": "Confidentialité des Données",
    "Sustainability": "Durabilité",
    "Contact": "Contact",
    "Partner Portal": "Portail Partenaires",
    "Support": "Support",
    "© 2026 Parcellino Swiss. Engineered in Zurich.": "© 2026 Parcellino Swiss. Conçu à Zurich.",
    "Terms": "Conditions",
    "Privacy": "Confidentialité",
    "Our warehouse automation reduces pick-error rates to less than 0.01%, ensuring your customers receive exactly what they ordered, every time.": "Notre automatisation d'entrepôt réduit les taux d'erreur de prélèvement à moins de 0,01 %, garantissant que vos clients reçoivent exactement ce qu'ils ont commandé, à chaque fois.",
    "Real-time Inventory Sync": "Synchro d'Inventaire en Temps Réel",
    "Same-day Dispatch (14:00 cutoff)": "Expédition le Jour Même (limite 14:00)",
    "Custom Brand Packaging": "Emballage de Marque Personnalisé",
    "Fragile Item Specialists": "Spécialistes des Articles Fragiles",
    "Luxury requires a different standard of care. We treat every parcel as a masterpiece, with dedicated white-glove inspection zones.": "Le luxe exige un niveau de soin différent. Nous traitons chaque colis comme un chef-d'œuvre, avec des zones d'inspection haut de gamme dédiées.",
    "Enhanced Security Vaults": "Coffres-forts de Sécurité Renforcés",
    "Climate Controlled Storage": "Stockage à Température Contrôlée",
    "Premium Tissue & Wax Seal handling": "Manipulation de Papier de Soie Premium & Sceaux de Cire",
    "Serial Number Tracking": "Suivi des Numéros de Série",
    "Precision is non-negotiable in medical logistics. Our facility meets the highest Swiss standards for pharmaceutical storage.": "La précision n'est pas négociable dans la logistique médicale. Notre installation répond aux normes suisses les plus élevées pour le stockage pharmaceutique.",
    "GDP Compliant Handling": "Manipulation Conforme aux BPD",
    "Cold Chain Logistics": "Logistique de la Chaîne du Froid",
    "Batch & Expiry Management": "Batch & Expiry Management",
    "Sterile Environment Options": "Options d'Environnement Stérile",
    "Returns are the second point of customer contact. We process returns in under 24 hours to ensure rapid restocking or liquidation.": "Les retours sont le deuxième point de contact client. Nous traitons les retours en moins de 24 heures pour garantir un réassort rapide ou une liquidation.",
    "Photo-Verified Inspections": "Inspections Vérifiées par Photo",
    "Quality Grading System": "Système de Classification de Qualité",
    "Rapid Customer Refunds": "Remboursements Clients Rapides",
    "Regional Consolidation": "Consolidation Régionale",
    "Cross-border trade shouldn't be a bottleneck. Our in-house customs experts ensure 100% compliance with EU and Swiss regulations.": "Le commerce transfrontalier ne devrait pas être un goulot d'étranglement. Nos experts en douane internes assurent une conformité à 100 % avec les réglementations de l'UE et de la Suisse.",
    "IOSS & OSS Management": "IOSS & OSS Management",
    "HS Code Classification": "Classification des Codes SH",
    "Duty & Tax Calculation": "Calcul des Droits & Taxes",
    "Frictionless EU-Swiss corridor": "Corridor UE-Suisse sans friction",
    "E-Com Management": "E-Com Management",
    "Engineered efficiency.": "L'efficacité conçue.",
    "Meticulous storage in our single, highly secure Swiss facility. Optimized storage space custom-tailored for early-stage brands.": "Un stockage méticuleux dans notre installation suisse unique et hautement sécurisée. Un espace de stockage optimisé sur mesure pour les marques en phase de démarrage.",
    "See How We Work": "Découvrez Notre Fonctionnement",
    "See Process": "Voir le Processus",
    "Swiss Warehousing": "Stockage Suisse",
    "View Storage": "Voir le Stockage",
    "We manually handle and process your Shopify, WooCommerce, and Amazon orders with Swiss precision. Perfect for emerging brands looking for error-free execution and personal care without complex setups.": "Nous gérons et traitons manuellement vos commandes Shopify, WooCommerce et Amazon avec une précision suisse. Parfait pour les marques émergentes recherchant un fulfillment sans erreur et des soins personnalisés sans configurations complexes.",
    "© 2026 Precision Fulfillment": "© 2026 Fulfillment de Précision",
    "We deliver more than products. We provide trust, efficiency and growth.": "Nous livrons plus que des produits. Nous fournissons de la confiance, de l'efficacité et de la croissance.",
    "100% Biodegradable Boxes": "Boîtes 100% Biodégradables",
    "60-Minute Picking Window": "Fenêtre de Prélèvement de 60 Minutes",
    "Carbon-Balanced Operations": "Opérations à Bilan Carbone Neutre",
    "Climate-Controlled Space": "Espace à Température Contrôlée",
    "Condition Grading Audit": "Audit d'Évaluation de l'État",
    "Custom Tailored Shelving": "Étagères Sur Mesure",
    "Deliver unforgettable premium unboxing moments with high-grade, sustainable materials certified for maximum shipping protection.": "Offrez des moments de déballage premium inoubliables avec des matériaux durables de haute qualité, certifiés pour une protection maximale lors de l'expédition.",
    "Eco-Certified Fillers": "Remplisseurs Éco-Certifiés",
    "Ensure immediate product validation and rapid restocking to maintain inventory liquidity and customer satisfaction.": "Assurez une validation immédiate des produits et un réassort rapide pour maintenir la liquidité des stocks et la satisfaction des clients.",
    "Express Dispatch Services": "Services d'Expédition Express",
    "High-Priority Scheduling": "Planification Hautement Prioritaire",
    "High-Security Protocols": "Protocoles de Haute Sécurité",
    "Instant Return Restocking": "Réassort Instantané des Retours",
    "Manual Quality Audit": "Audit de Qualité Manuel",
    "Our swift picking processes move with synchronized precision, minimizing transit delays and expediting shipping times.": "Nos processus de prélèvement rapides fonctionnent avec une précision synchronisée, minimisant les délais de transit et accélérant les temps d'expédition.",
    "Personalized Client Dashboard": "Tableau de Bord Client Personnalisé",
    "Premium Custom Branding": "Marque Personnalisée Premium",
    "Shopify & WooCommerce Integration": "Intégration Shopify & WooCommerce",
    "Single Secure Swiss Facility": "Installation Suisse Sécurisée Unique",
    "Swift Customer Status Updates": "Mises à Jour Rapides du Statut Client",
    "Verification & Inspection": "Vérification & Inspection",
    "We process orders with absolute white-glove manual precision, ensuring 100% accuracy and customized attention for emerging brands.": "Nous traitons les commandes avec une précision manuelle absolue de haut niveau, garantissant une exactitude de 100 % et une attention personnalisée pour les marques émergentes.",
    "Your inventory is protected within our single state-of-the-art secure Swiss facility with optimized shelving and strict climate control.": "Votre inventaire est protégé au sein de notre installation suisse sécurisée et à la pointe de la technologie, avec des étagères optimisées et un contrôle climatique strict.",
    "Zero Pick-Error Tolerance": "Tolérance Zéro pour les Erreurs de Prélèvement",
    "Zero-Setup Complexities": "Zéro Complexité d'Installation",
    "Swiss Ambition": "L'Ambition Suisse",
    "Our company was established by a ": "Notre entreprise a été fondée par une ",
    "woman entrepreneur": "femme entrepreneuse",
    " who has seen and felt the pain in the fulfillment process, and we have a ": " qui a vu et ressenti la douleur du processus de fulfillment, et nous avons une ",
    "simple vision": "vision simple",
    " to make fulfillment ": " pour rendre le fulfillment ",
    "seamless, reliable and exceptional": "fluide, fiable et exceptionnelle",
    "Smart logistics, proactive service and uncompromising attention to detail": "Une logistique intelligente, un service proactif et une attention intransigeante aux détails",
    ", all for the purpose of ensuring that the quality of our service is reflected in every order you place.": ", tout cela dans le but de s'assurer que la qualité de notre service se reflète dans chaque commande que vous passez.",
    "We deliver more than products.": "Nous livrons plus que des produits.",
    "We provide trust, efficiency and growth.": "Nous fournissons de la confiance, de l'efficacité et de la croissance.",
    "WhatsApp": "WhatsApp",
    "Pioneering Swiss fulfillment and E-commerce logistics Switzerland solutions. From the heart of the nation, we provide real-time logistics and the Swiss standard of reliability.": "Pionniers des solutions de fulfillment suisses et de logistique e-commerce en Suisse. Du cœur de la nation, nous fournissons une logistique en temps réel et la norme de fiabilité suisse.",
    "Premier Shopify fulfillment Switzerland services. We manually handle and process your Shopify, WooCommerce, and Amazon orders with Swiss precision, offering error-free care without complexities.": "Les meilleurs services de fulfillment Shopify en Suisse. Nous gérons et traitons manuellement vos commandes Shopify, WooCommerce et Amazon avec une précision suisse, offrant un soin sans erreur et sans complexité.",
    "Leading provider of fulfillment Switzerland services and precision architecture.": "Fournisseur leader de services de fulfillment en Suisse et d'architecture de précision.",
    "Nationwide": "National",
    "Client Success": "Succès Client",
    "Trusted by Industry Leaders": "Approuvé par les Leaders de l'Industrie",
    "We have been working with Parcellino in IT/logistics for our brand Hydrux for some time now... The cooperation is efficient, reliable, and absolutely professional.": "Nous travaillons avec Parcellino dans le domaine de l'informatique/logistique pour notre marque Hydrux depuis un certain temps maintenant... La coopération est efficace, fiable et absolument professionnelle.",
    "Parcellino takes over our fulfillment and we at dirts benefit from the fast processing... Parcellino is the perfect partner.": "Parcellino prend en charge notre fulfillment et nous, chez dirts, bénéficions du traitement rapide... Parcellino est le partenaire idéal.",
    "By outsourcing our warehouse and fulfillment, we benefited on our core competencies while being sure this part is handled professionally.": "En externalisant notre entrepôt et notre fulfillment, nous nous sommes concentrés sur nos compétences principales tout en étant sûrs que cette partie est gérée professionnellement.",
    "Founder": "Fondateur",
    "Swiss Precision Warehouse": "Entrepôt de Précision Suisse",
    "Swiss Logistics Network": "Réseau Logistique Suisse",
    "Toggle Theme": "Basculer le Thème"
  },
  Italiano: {
    "Home": "Home",
    "Solutions": "Soluzioni",
    "Start Your E-com Now": "Inizia ora il tuo E-com",
    "Start Fulfillment": "Inizia Fulfillment",
    "Select Language": "Seleziona Lingua",
    "Contact Architecture": "Architettura dei Contatti",
    "THE SWISS LOGISTICS EDGE": "IL VANTAGGIO LOGISTICO SVIZZERO",
    "PARCELLINO": "PARCELLINO",
    "PRECISION": "PRECISIONE",
    "FULFILLMENT": "FULFILLMENT",
    "From the heart of Switzerland to every corner of the nation. Real-time logistics, multi-language integration, and the Swiss standard of reliability.": "Dal cuore della Svizzera ad ogni angolo della nazione. Logistica in tempo reale, integrazione multilingue e lo standard svizzero di affidabilità.",
    "See our solutions": "Scopri le nostre soluzioni",
    "View Network": "Visualizza Rete",
    "System Status": "Stato del Sistema",
    "26 Cantons": "26 Cantoni",
    "100% NATIONWIDE COVERAGE": "100% COPERTURA NAZIONALE",
    "Seamless local fulfillment from Zurich to Geneva.": "Fulfillment locale fluido da Zurigo a Ginevra.",
    "Scroll to explore": "Scorri per esplorare",
    "Swiss coverage is": "La copertura svizzera è",
    "absolute": "assoluta",
    "Our infrastructure is optimized exclusively for the Swiss landscape. From Geneva to Zurich, Lugano to Basel, we provide flawless fulfillment tailored perfectly to Switzerland's unique multi-language cantons.": "La nostra infrastruttura è ottimizzata esclusivamente per il paesaggio svizzero. Da Ginevra a Zurigo, da Lugano a Basilea, forniamo un fulfillment impeccabile adattato perfettamente ai cantoni multilingue unici della Svizzera.",
    "SWISS MULTI-LANGUAGE ARCHITECTURE": "ARCHITETTURA MULTILINGUE SVIZZERA",
    "ENGINEERED EXCELLENENCE": "ECCELLENZA INGEGNERISTICA",
    "ECOSYSTEM OF PRECISION": "ECOSISTEMA DI PRECISIONE",
    "E-Com Integration": "Integrazione E-Com",
    "One-click Shopify/Woo/Amazon sync. Our system ensures your stock levels are never out of sync.": "Sincronizzazione con un clic su Shopify/Woo/Amazon. Il nostro sistema garantisce che i tuoi livelli di stock non siano mai fuori sincrono.",
    "Explore Tech": "Esplora la Tecnologia",
    "Sustainable Packaging": "Imballaggio Sostenibile",
    "The future of eco-conscious delivery. 100% biodegradable materials engineered for structural integrity and premium unboxing experiences.": "Il futuro delle consegne eco-consapevoli. Materiali 100% biodegradabili progettati per integrità strutturale ed esperienze di unboxing premium.",
    "View Eco-Policy": "Visualizza Politica Ecologica",
    "Rapid Fulfillment": "Fulfillment Rapido",
    "Order-to-shipping in 60 minutes. Meticulous picking flows engineered for maximum efficiency.": "Dall'ordine alla spedizione in 60 minuti. Flussi di prelievo meticolosi progettati per la massima efficienza.",
    "Returns Management": "Returns Management",
    "Automated verification and instant restocking for peak efficiency.": "Verifica automatizzata e rifornimento istantaneo per la massima efficienza.",
    "MISSION-CRITICAL SUPPORT": "SUPPORTO CRITICO",
    "ORDER ACCURACY RATE": "TASSO DI PRECISIONE DEGLI ORDINI",
    "STRATEGIC REACH": "PORTATA STRATEGICA",
    "Solutions Architecture": "Architettura delle Soluzioni",
    "Tailored Logistics for": "Logistica su Misura per",
    "Swiss Ambition.": "Ambizione Svizzera.",
    "Swiss-engineered precision for industries that demand perfection.": "Precisione ingegneristica svizzera per industrie che esigono perfezione.",
    "Powering Swiss Trade Leaders": "Alimentare i Leader Commerciali Svizzeri",
    "E-Commerce Fulfillment": "Fulfillment E-Commerce",
    "Seamlessly scale your D2C brand with high-volume, precision-driven order processing. From pick & pack to last-mile — we architect speed.": "Scala il tuo brand D2C in modo fluido con un'elaborazione degli ordini ad alto volume basata sulla precisione. Dal pick & pack all'ultimo miglio — progettiamo la velocità.",
    "Explore this solution": "Esplora questa soluzione",
    "Luxury Goods Handling": "Luxury Goods Handling",
    "White-glove treatment with enhanced security, premium unboxing experiences, and meticulous care for your most valuable inventory.": "Trattamento premium con sicurezza potenziata, esperienze di unboxing esclusive e cura meticolosa per il tuo inventario più prezioso.",
    "Medical & High-Value": "Medico e Alto Valore",
    "Temperature-controlled environments and strict compliance protocols for sensitive inventories that demand zero-tolerance accuracy.": "Ambienti a temperatura controllata e protocolli di conformità rigorosi per inventari sensibili che richiedono precisione a tolleranza zero.",
    "Returns Management (Desc)": "Ispezioni di qualità automatizzate e rifornimento rapido per proteggere i tuoi margini. Trasforma i resi in entrate conservate e fiducia rinnovata.",
    "Swiss Cantonal Logistics": "Logistica Cantonale Svizzera",
    "Flawless delivery across all 26 cantons with optimized route networks and localized language handling. We cover Switzerland perfectly so you can focus on local growth.": "Consegna impeccabile in tutti i 26 cantoni con reti di percorsi ottimizzate e gestione linguistica localizzata. Copriamo perfettamente la Svizzera per farti concentrare sulla crescita locale.",
    "Deep Architecture — ": "Architettura Profonda — ",
    "Expert Insight": "Intuizione degli Esperti",
    "Core Capabilities": "Capacità Principali",
    "Ready to discuss this architecture for your brand?": "Pronto a discutere questa architettura per il tuo brand?",
    "Schedule Technical Brief": "Pianifica Briefing Tecnico",
    "The Parcellino Advantage": "Il Vantaggio Parcellino",
    "Swiss Precision": "Precisione Svizzera",
    "99.9% fulfillment accuracy across all sectors.": "Precisione di fulfillment del 99,9% in tutti i settori.",
    "Swiss-wide Coverage": "Copertura in Tutta la Svizzera",
    "Direct lanes to all 26 cantons.": "Linee dirette a tutti i 26 cantoni.",
    "Eco-Friendly / Swiss Made": "Ecologico / Prodotto in Svizzera",
    "\"Sustainable Packaging & Carbon-Balanced Logistics\"": "\"Imballaggi Sostenibili e Logistica a Impatto Neutro\"",
    "We engineer customized, eco-friendly unboxing experiences that align with your brand values while mitigating environmental impact through optimized shipping routes and climate-neutral partners.": "Progettiamo esperienze di unboxing personalizzate ed ecologiche che si allineano con i valori del tuo brand mitigando l'impatto ambientale attraverso percorsi ottimizzati e partner climaticamente neutri.",
    "Request Strategy": "Richiedi Strategia",
    "Common Inquiries": "Domande Comuni",
    "Frequently Asked Questions": "Domande Frequenti",
    "What is your typical turnaround for e-commerce integration?": "Qual è il vostro tempo di risposta tipico per l'integrazione e-commerce?",
    "Most major platforms (Shopify, WooCommerce, Amazon) can be integrated within 24-48 hours. Our technical team provides end-to-end support for custom API setups.": "La maggior parte delle piattaforme (Shopify, WooCommerce, Amazon) può essere integrata in 24-48 ore. Il nostro team tecnico fornisce supporto completo per le configurazioni API personalizzate.",
    "Do you deliver to alpine and remote Swiss regions?": "Consegnate in regioni alpine e svizzere remote?",
    "Yes. We deliver to every single valley and mountain village across all 26 cantons with our specialized Swiss logistics partners, guaranteeing on-time arrival.": "Sì. Consegniamo in ogni singola valle e villaggio di montagna in tutti i 26 cantoni con i nostri partner logistici svizzeri specializzati, garantendo arrivi puntuali.",
    "Are your packaging materials eco-friendly?": "I vostri materiali di imballaggio sono ecologici?",
    "Yes. We use 100% biodegradable, climate-neutral materials engineered specifically for safe, premium, and sustainable unboxing experiences across Switzerland.": "Sì. Utilizziamo materiali biodegradabili al 100% e climaticamente neutri, progettati specificamente per esperienze di unboxing sicure, di lusso e sostenibili in tutta la Svizzera.",
    "How does your returns management process work?": "Come funziona il vostro processo di returns management?",
    "Our automated returns portal allows customers to initiate returns easily. Once received, we perform rapid quality checks and restock or process according to your brand's specific protocols.": "Il nostro portale di resi automatizzato consente ai clienti di avviare facilmente un reso. Una volta ricevuti, eseguiamo rapidi controlli di qualità e riforniamo o elaboriamo secondo i protocolli del tuo brand.",
    "SWISS LEADERSHIP": "LEADERSHIP SVIZZERA",
    "Logistics is the": "La logistica è il",
    "heartbeat": "battito del cuore",
    "of your brand. We make sure it never skips a beat.": "del tuo brand. Ci assicuriamo che non salti mai un battito.",
    "Founder & CEO": "Fondatrice e CEO",
    "VOICES OF PARTNERSHIP": "VOCI DI PARTNERSHIP",
    "THEY TRUST PARCELLINO.": "LORO SI FIDANO DI PARCELLINO.",
    "Since migrating to Parcellino, our order-to-door time in DACH dropped by 40%. Their fulfillment precision is nothing short of Swiss.": "Da quando siamo passati a Parcellino, il nostro tempo ordine-consegna nella regione DACH è diminuito del 40%. La loro precisione di fulfillment non è niente meno che svizzera.",
    "Operations Director, Velox Wear": "Direttore Operativo, Velox Wear",
    "We needed a partner who treats luxury goods with respect. Parcellino’s white-glove service transformed our customer unboxing experience.": "Avevamo bisogno di un partner che trattasse i beni di lusso con rispetto. Il servizio premium di Parcellino ha trasformato la nostra esperienza di unboxing dei clienti.",
    "Founder, Lumina Swiss": "Fondatore, Lumina Swiss",
    "Ready to Scale Your Logistics?": "Pronto a Scalare la Tua Logistica?",
    "Connect with our solutions architects for a tailored technical brief and Swiss scaling strategy.": "Connettiti con i nostri architetti delle soluzioni per un briefing tecnico su misura e una strategia di ridimensionamento svizzera.",
    "Book a Strategy Call": "Prenota una Chiamata Strategica",
    "Speak to an Expert Now": "Parla Ora con un Esperto",
    "SCALABILITY": "SCALABILITÀ",
    "READY TO UPGRADE": "PRONTO PER L'AGGIORNAMENTO",
    "YOUR ARCHITECTURE?": "DELLA TUA ARCHITETTURA?",
    "Join leading D2C brands leveraging Swiss precision for nationwide growth.": "Unisciti ai principali marchi D2C che sfruttano la precisione svizzera per la crescita nazionale.",
    "Initiate Integration": "Inizia Integrazione",
    "Or contact our engineering team": "O contatta il nostro team di ingegneri",
    "Switzerland's premier fulfillment architecture. Precision, speed, and neutrality for local commerce.": "La principale architettura di fulfillment della Svizzera. Precisione, velocità e neutralità per il commercio locale.",
    "Zürich, Switzerland": "Zurigo, Svizzera",
    "Operations": "Operazioni",
    "E-Com Sync": "Sincronizzazione E-Com",
    "Luxury Handing": "Luxury Handing",
    "Returns AI": "AI dei Resi",
    "Customs API": "API Doganali",
    "Architecture": "Architettura",
    "Network Map": "Mappa della Rete",
    "Security": "Sicurezza",
    "Data Privacy": "Privacy dei Dati",
    "Sustainability": "Sostenibilità",
    "Contact": "Contatto",
    "Partner Portal": "Portale Partner",
    "Support": "Supporto",
    "© 2026 Parcellino Swiss. Engineered in Zurich.": "© 2026 Parcellino Swiss. Progettato a Zurigo.",
    "Terms": "Termini",
    "Privacy": "Privacy",
    "Our warehouse automation reduces pick-error rates to less than 0.01%, ensuring your customers receive exactly what they ordered, every time.": "La nostra automazione del magazzino riduce il tasso di errori di prelievo a meno dello 0,01%, assicurando che i tuoi clienti ricevano esattamente ciò che hanno ordinato, ogni volta.",
    "Real-time Inventory Sync": "Sincronizzazione Inventario in Tempo Reale",
    "Same-day Dispatch (14:00 cutoff)": "Spedizione in Giornata (limite 14:00)",
    "Custom Brand Packaging": "Imballaggio Personalizzato del Brand",
    "Fragile Item Specialists": "Specialisti Articoli Fragili",
    "Luxury requires a different standard of care. We treat every parcel as a masterpiece, with dedicated white-glove inspection zones.": "Il lusso richiede un diverso standard di cura. Trattiamo ogni pacco come un capolavoro, con zone di ispezione premium dedicate.",
    "Enhanced Security Vaults": "Caveau di Sicurezza Potenziati",
    "Climate Controlled Storage": "Stoccaggio a Temperatura Controllata",
    "Premium Tissue & Wax Seal handling": "Premium Tissue & Wax Seal handling",
    "Serial Number Tracking": "Tracciamento Numero di Serie",
    "Precision is non-negotiable in medical logistics. Our facility meets the highest Swiss standards for pharmaceutical storage.": "La precisione non è negoziabile nella logistica medica. La nostra struttura soddisfa i più alti standard svizzeri per la conservazione farmaceutica.",
    "GDP Compliant Handling": "GDP Compliant Handling",
    "Cold Chain Logistics": "Logistica Catena del Freddo",
    "Batch & Expiry Management": "Batch & Expiry Management",
    "Sterile Environment Options": "Opzioni Ambiente Sterile",
    "Returns are the second point of customer contact. We process returns in under 24 hours to ensure rapid restocking or liquidation.": "I resi sono il secondo punto di contatto con il cliente. Elaboriamo i resi in meno di 24 ore per garantire un rifornimento rapido o la liquidazione.",
    "Photo-Verified Inspections": "Ispezioni Verificate Fotograficamente",
    "Quality Grading System": "Sistema di Classificazione Qualità",
    "Rapid Customer Refunds": "Rimborsi Clienti Rapidi",
    "Regional Consolidation": "Consolidamento Regionale",
    "Cross-border trade shouldn't be a bottleneck. Our in-house customs experts ensure 100% compliance with EU and Swiss regulations.": "Il commercio transfrontaliero non dovrebbe essere un collo di bottiglia. I nostri esperti doganali interni assicurano il 100% di conformità con le normative UE e svizzere.",
    "IOSS & OSS Management": "IOSS & OSS Management",
    "HS Code Classification": "Classificazione Codici HS",
    "Duty & Tax Calculation": "Calcolo Dazi e Tasse",
    "Frictionless EU-Swiss corridor": "Corridoio UE-Svizzera senza attriti",
    "E-Com Management": "E-Com Management",
    "Engineered efficiency.": "Efficienza ingegnerizzata.",
    "Meticulous storage in our single, highly secure Swiss facility. Optimized storage space custom-tailored for early-stage brands.": "Stoccaggio meticoloso nella nostra singola struttura svizzera ad alta sicurezza. Spazio di stoccaggio ottimizzato su misura per i brand emergenti.",
    "See How We Work": "Scopri Come Lavoriamo",
    "See Process": "Visualizza Processo",
    "Swiss Warehousing": "Stoccaggio Svizzero",
    "View Storage": "Visualizza Stoccaggio",
    "We manually handle and process your Shopify, WooCommerce, and Amazon orders with Swiss precision. Perfect for emerging brands looking for error-free execution and personal care without complex setups.": "Gestiamo ed elaboriamo manualmente i tuoi ordini Shopify, WooCommerce e Amazon con precisione svizzera. Perfetto per i brand emergenti che cercano un'esecuzione senza errori e attenzione personale senza configurazioni complesse.",
    "© 2026 Precision Fulfillment": "© 2026 Fulfillment di Precisione",
    "We deliver more than products. We provide trust, efficiency and growth.": "Consegniamo più di semplici prodotti. Forniamo fiducia, efficienza e crescita.",
    "100% Biodegradable Boxes": "Scatole 100% Biodegradabili",
    "60-Minute Picking Window": "Finestra di Prelievo di 60 Minuti",
    "Carbon-Balanced Operations": "Operazioni a Bilancio di Carbonio Neutro",
    "Climate-Controlled Space": "Spazio a Temperatura Controllata",
    "Condition Grading Audit": "Verifica della Classificazione delle Condizioni",
    "Custom Tailored Shelving": "Scaffalature su Misura",
    "Deliver unforgettable premium unboxing moments with high-grade, sustainable materials certified for maximum shipping protection.": "Regala momenti indimenticabili di unboxing premium con materiali sostenibili di alta qualità, certificati per la massima protezione della spedizione.",
    "Eco-Certified Fillers": "Riempitivi Eco-Certificati",
    "Ensure immediate product validation and rapid restocking to maintain inventory liquidity and customer satisfaction.": "Assicuriamo l'immediata validazione del prodotto e un rapido rifornimento per mantenere la liquidità dell'inventario e la soddisfazione del cliente.",
    "Express Dispatch Services": "Servizi di Spedizione Express",
    "High-Priority Scheduling": "Programmazione ad Alta Priorità",
    "High-Security Protocols": "Protocolli di Alta Sicurezza",
    "Instant Return Restocking": "Rifornimento Istantaneo dei Resi",
    "Manual Quality Audit": "Controllo di Qualità Manuale",
    "Our swift picking processes move with synchronized precision, minimizing transit delays and expediting shipping times.": "I nostri rapidi processi di prelievo si muovono con precisione sincronizzata, minimizzando i ritardi di transito e accelerando i tempi di spedizione.",
    "Personalized Client Dashboard": "Dashboard Cliente Personalizzata",
    "Premium Custom Branding": "Branding Personalizzato Premium",
    "Shopify & WooCommerce Integration": "Integrazione Shopify e WooCommerce",
    "Single Secure Swiss Facility": "Singola Struttura Sicura in Svizzera",
    "Swift Customer Status Updates": "Aggiornamenti Rapidi di Stato per i Clienti",
    "Verification & Inspection": "Verifica e Ispezione",
    "We process orders with absolute white-glove manual precision, ensuring 100% accuracy and customized attention for emerging brands.": "Elaboriamo gli ordini con assoluta precisione manuale d'eccellenza, garantendo l'accuratezza del 100% e attenzione personalizzata per i brand emergenti.",
    "Your inventory is protected within our single state-of-the-art secure Swiss facility with optimized shelving and strict climate control.": "Il tuo inventario è protetto all'interno della nostra singola struttura svizzera sicura all'avanguardia con scaffalature ottimizzate e rigoroso controllo climatico.",
    "Zero Pick-Error Tolerance": "Tolleranza Zero per gli Errori di Prelievo",
    "Zero-Setup Complexities": "Zero Complessità di Configurazione",
    "Swiss Ambition": "Ambizione Svizzera",
    "Our company was established by a ": "La nostra azienda è stata fondata da un' ",
    "woman entrepreneur": "imprenditrice",
    " who has seen and felt the pain in the fulfillment process, and we have a ": " che ha vissuto e sentito i problemi del processo di fulfillment, e abbiamo una ",
    "simple vision": "semplice visione",
    " to make fulfillment ": " per rendere il fulfillment ",
    "seamless, reliable and exceptional": "fluido, affidabile ed eccezionale",
    "Smart logistics, proactive service and uncompromising attention to detail": "Logistica intelligente, servizio proattivo e attenzione senza compromessi ai dettagli",
    ", all for the purpose of ensuring that the quality of our service is reflected in every order you place.": ", tutto con lo scopo di garantire che la qualità del nostro servizio si rifletta in ogni ordine che effettui.",
    "We deliver more than products.": "Consegniamo più di semplici prodotti.",
    "We provide trust, efficiency and growth.": "Forniamo fiducia, efficienza e crescita.",
    "WhatsApp": "WhatsApp",
    "Pioneering Swiss fulfillment and E-commerce logistics Switzerland solutions. From the heart of the nation, we provide real-time logistics and the Swiss standard of reliability.": "Soluzioni pionieristiche per il fulfillment e la logistica e-commerce in Svizzera. Dal cuore della nazione, forniamo logistica in tempo reale e lo standard svizzero di affidabilità.",
    "Premier Shopify fulfillment Switzerland services. We manually handle and process your Shopify, WooCommerce, and Amazon orders with Swiss precision, offering error-free care without complexities.": "Servizi premium di fulfillment per Shopify in Svizzera. Gestiamo ed elaboriamo manualmente i tuoi ordini Shopify, WooCommerce e Amazon con precisione svizzera, offrendo un servizio senza errori e senza complessità.",
    "Leading provider of fulfillment Switzerland services and precision architecture.": "Fornitore leader di servizi di fulfillment in Svizzera e architettura di precisione.",
    "Nationwide": "Nazionale",
    "Client Success": "Successo dei Clienti",
    "Trusted by Industry Leaders": "Scelto dai Leader del Settore",
    "We have been working with Parcellino in IT/logistics for our brand Hydrux for some time now... The cooperation is efficient, reliable, and absolutely professional.": "Lavoriamo con Parcellino per IT e logistica per il nostro marchio Hydrux da tempo ormai... La collaborazione è efficiente, affidabile e assolutamente professionale.",
    "Parcellino takes over our fulfillment and we at dirts benefit from the fast processing... Parcellino is the perfect partner.": "Parcellino si occupa del nostro fulfillment e noi di dirts beneficiamo di un'elaborazione veloce... Parcellino è il partner perfetto.",
    "By outsourcing our warehouse and fulfillment, we benefited on our core competencies while being sure this part is handled professionally.": "Esternalizzando il nostro magazzino e il fulfillment, ci siamo potuti concentrare sulle nostre competenze principali con la certezza che questa parte sia gestita in modo professionale.",
    "Founder": "Fondatore",
    "Swiss Precision Warehouse": "Magazzino di Precisione Svizzero",
    "Swiss Logistics Network": "Rete Logistica Svizzera",
    "Toggle Theme": "Cambia Tema"
  },
  Español: {
    "Home": "Inicio",
    "Solutions": "Soluciones",
    "Start Your E-com Now": "Inicia tu E-com Ahora",
    "Start Fulfillment": "Iniciar Fulfillment",
    "Select Language": "Seleccionar Idioma",
    "Contact Architecture": "Arquitectura de Contacto",
    "THE SWISS LOGISTICS EDGE": "LA VENTAJA LOGÍSTICA SUIZA",
    "PARCELLINO": "PARCELLINO",
    "PRECISION": "PRECISIÓN",
    "FULFILLMENT": "FULFILLMENT",
    "From the heart of Switzerland to every corner of the nation. Real-time logistics, multi-language integration, and the Swiss standard of reliability.": "Desde el corazón de Suiza hasta cada rincón de la nación. Logística en tiempo real, integración multilingüe y el estándar suizo de fiabilidad.",
    "See our solutions": "Ver nuestras soluciones",
    "View Network": "Ver Red",
    "System Status": "Estado del Sistema",
    "26 Cantons": "26 Cantones",
    "100% NATIONWIDE COVERAGE": "100% COBERTURA NACIONAL",
    "Seamless local fulfillment from Zurich to Geneva.": "Fulfillment local fluido de Zúrich a Ginebra.",
    "Scroll to explore": "Desplázate para explorar",
    "Swiss coverage is": "La cobertura suiza es",
    "absolute": "absoluta",
    "Our infrastructure is optimized exclusively for the Swiss landscape. From Geneva to Zurich, Lugano to Basel, we provide flawless fulfillment tailored perfectly to Switzerland's unique multi-language cantons.": "Nuestra infraestructura está optimizada exclusivamente para el paisaje suizo. De Ginebra a Zúrich, de Lugano a Basilea, proporcionamos un fulfillment impecable adaptado perfectamente a los cantones multilingües únicos de Suiza.",
    "SWISS MULTI-LANGUAGE ARCHITECTURE": "ARQUITECTURA MULTILINGÜE SUIZA",
    "ENGINEERED EXCELLENCE": "EXCELENCIA DE INGENIERÍA",
    "ECOSYSTEM OF PRECISION": "ECOSISTEMA DE PRECISIÓN",
    "E-Com Integration": "Integración E-Com",
    "One-click Shopify/Woo/Amazon sync. Our system ensures your stock levels are never out of sync.": "Sincronización con un clic en Shopify/Woo/Amazon. Nuestro sistema asegura que tus niveles de stock nunca estén desincronizados.",
    "Explore Tech": "Explorar Tecnología",
    "Sustainable Packaging": "Embalaje Sostenible",
    "The future of eco-conscious delivery. 100% biodegradable materials engineered for structural integrity and premium unboxing experiences.": "El futuro de las entregas eco-conscientes. Materiales 100% biodegradables diseñados para integridad estructural y experiencias de unboxing premium.",
    "View Eco-Policy": "Ver Política Ecológica",
    "Rapid Fulfillment": "Fulfillment Rápido",
    "Order-to-shipping in 60 minutes. Meticulous picking flows engineered for maximum efficiency.": "De orden a envío en 60 minutos. Flujos de picking meticulosos diseñados para la máxima eficiencia.",
    "Returns Management": "Returns Management",
    "Automated verification and instant restocking for peak efficiency.": "Verificación automatizada y reposición instantánea para máxima eficiencia.",
    "MISSION-CRITICAL SUPPORT": "SOPORTE CRÍTICO",
    "ORDER ACCURACY RATE": "TASA DE PRECISIÓN DE PEDIDOS",
    "STRATEGIC REACH": "ALCANCE ESTRATÉGICO",
    "Solutions Architecture": "Arquitectura de Soluciones",
    "Tailored Logistics for": "Logística a Medida para",
    "Swiss Ambition.": "Ambición Suiza.",
    "Swiss-engineered precision for industries that demand perfection.": "Precisión de ingeniería suiza para industrias que exigen perfección.",
    "Powering Swiss Trade Leaders": "Impulsando a los Líderes del Comercio Suizo",
    "E-Commerce Fulfillment": "Fulfillment E-Commerce",
    "Seamlessly scale your D2C brand with high-volume, precision-driven order processing. From pick & pack to last-mile — we architect speed.": "Escala tu marca D2C sin problemas con procesamiento de pedidos de alto volumen guiado por precisión. Desde pick & pack hasta la última milla — diseñamos velocidad.",
    "Explore this solution": "Explorar esta solución",
    "Luxury Goods Handling": "Manejo de Artículos de Lujo",
    "White-glove treatment with enhanced security, premium unboxing experiences, and meticulous care for your most valuable inventory.": "Tratamiento de guante blanco con seguridad mejorada, experiencias de unboxing premium y un cuidado meticuloso para tu inventario más valioso.",
    "Medical & High-Value": "Médico y de Alto Valor",
    "Temperature-controlled environments and strict compliance protocols for sensitive inventories that demand zero-tolerance accuracy.": "Entornos con temperatura controlada y estrictos protocolos de cumplimiento para inventarios sensibles que exigen precisión de cero tolerancia.",
    "Returns Management (Desc)": "Inspecciones de calidad automatizadas y reposición rápida para proteger tus márgenes. Transforma las devoluciones en ingresos retenidos y confianza renovada.",
    "Swiss Cantonal Logistics": "Logística Cantonal Suiza",
    "Flawless delivery across all 26 cantons with optimized route networks and localized language handling. We cover Switzerland perfectly so you can focus on local growth.": "Entrega impecable en los 26 cantones con redes de rutas optimizadas y manejo localizado de idiomas. Cubrimos Suiza a la perfección para que puedas concentrarte en el crecimiento local.",
    "Deep Architecture — ": "Arquitectura Profunda — ",
    "Expert Insight": "Visión de Expertos",
    "Core Capabilities": "Capacidades Básicas",
    "Ready to discuss this architecture for your brand?": "¿Listo para discutir esta arquitectura para tu marca?",
    "Schedule Technical Brief": "Programar Resumen Técnico",
    "The Parcellino Advantage": "La Ventaja Parcellino",
    "Swiss Precision": "Precisión Suiza",
    "99.9% fulfillment accuracy across all sectors.": "99.9% de precisión en fulfillment en todos los sectores.",
    "Swiss-wide Coverage": "Cobertura en Toda Suiza",
    "Direct lanes to all 26 cantons.": "Rutas directas a los 26 cantones.",
    "Eco-Friendly / Swiss Made": "Ecológico / Hecho en Suiza",
    "\"Sustainable Packaging & Carbon-Balanced Logistics\"": "\"Embalaje Sostenible y Logística con Balance de Carbono\"",
    "We engineer customized, eco-friendly unboxing experiences that align with your brand values while mitigating environmental impact through optimized shipping routes and climate-neutral partners.": "Diseñamos experiencias de unboxing ecológicas personalizadas que se alinean con los valores de tu marca mientras mitigamos el impacto ambiental a través de rutas de envío optimizadas y socios climáticamente neutros.",
    "Request Strategy": "Solicitar Estrategia",
    "Common Inquiries": "Consultas Comunes",
    "Frequently Asked Questions": "Preguntas Frecuentes",
    "What is your typical turnaround for e-commerce integration?": "¿Cuál es su tiempo de respuesta típico para la integración de e-commerce?",
    "Most major platforms (Shopify, WooCommerce, Amazon) can be integrated within 24-48 hours. Our technical team provides end-to-end support for custom API setups.": "La mayoría de las plataformas principales (Shopify, WooCommerce, Amazon) se pueden integrar en 24-48 horas. Nuestro equipo técnico proporciona soporte integral para configuraciones de API personalizadas.",
    "Do you deliver to alpine and remote Swiss regions?": "¿Entregan en regiones alpinas y remotas de Suiza?",
    "Yes. We deliver to every single valley and mountain village across all 26 cantons with our specialized Swiss logistics partners, guaranteeing on-time arrival.": "Sí. Entregamos a cada valle y pueblo de montaña en los 26 cantones con nuestros socios logísticos suizos especializados, garantizando llegadas a tiempo.",
    "Are your packaging materials eco-friendly?": "¿Son ecológicos sus materiales de embalaje?",
    "Yes. We use 100% biodegradable, climate-neutral materials engineered specifically for safe, premium, and sustainable unboxing experiences across Switzerland.": "Sí. Utilizamos materiales 100% biodegradables y neutros en carbono diseñados específicamente para experiencias de unboxing seguras, premium y sostenibles en toda Suiza.",
    "How does your returns management process work?": "¿Cómo funciona su proceso de returns management?",
    "Our automated returns portal allows customers to initiate returns easily. Once received, we perform rapid quality checks and restock or process according to your brand's specific protocols.": "Nuestro portal automatizado de devoluciones permite a los clientes iniciar devoluciones fácilmente. Una vez recibidas, realizamos comprobaciones rápidas de calidad y reabastecemos o procesamos de acuerdo con los protocolos específicos de tu marca.",
    "SWISS LEADERSHIP": "LIDERAZGO SUIZO",
    "Logistics is the": "La logística es el",
    "heartbeat": "latido",
    "of your brand. We make sure it never skips a beat.": "de tu marca. Nos aseguramos de que nunca se salte un latido.",
    "Founder & CEO": "Fundadora y CEO",
    "VOICES OF PARTNERSHIP": "VOCES DE ASOCIACIÓN",
    "THEY TRUST PARCELLINO.": "CONFÍAN EN PARCELLINO.",
    "Since migrating to Parcellino, our order-to-door time in DACH dropped by 40%. Their fulfillment precision is nothing short of Swiss.": "Desde que migramos a Parcellino, nuestro tiempo de pedido a puerta en la región DACH se redujo en un 40%. Su precisión en fulfillment es simplemente suiza.",
    "Operations Director, Velox Wear": "Director de Operaciones, Velox Wear",
    "We needed a partner who treats luxury goods with respect. Parcellino’s white-glove service transformed our customer unboxing experience.": "Necesitábamos un socio que tratara los artículos de lujo con respeto. El servicio de guante blanco de Parcellino transformó la experiencia de unboxing de nuestros clientes.",
    "Founder, Lumina Swiss": "Fundador, Lumina Swiss",
    "Ready to Scale Your Logistics?": "¿Listo para Escalar tu Logística?",
    "Connect with our solutions architects for a tailored technical brief and Swiss scaling strategy.": "Conéctate con nuestros arquitectos de soluciones para un resumen técnico a medida y una estrategia de escalado suiza.",
    "Book a Strategy Call": "Reservar una Llamada de Estrategia",
    "Speak to an Expert Now": "Hablar con un Experto Ahora",
    "SCALABILITY": "ESCALABILIDAD",
    "READY TO UPGRADE": "¿LISTO PARA ACTUALIZAR",
    "YOUR ARCHITECTURE?": "TU ARQUITECTURA?",
    "Join leading D2C brands leveraging Swiss precision for nationwide growth.": "Únete a marcas líderes de D2C que aprovechan la precisión suiza para el crecimiento nacional.",
    "Initiate Integration": "Iniciar Integración",
    "Or contact our engineering team": "O contacta a nuestro equipo de ingeniería",
    "Switzerland's premier fulfillment architecture. Precision, speed, and neutrality for local commerce.": "La principal arquitectura de fulfillment de Suiza. Precisión, velocidad y neutralidad para el comercio local.",
    "Zürich, Switzerland": "Zúrich, Suiza",
    "Operations": "Operaciones",
    "E-Com Sync": "Sincronización E-Com",
    "Luxury Handing": "Manejo de Lujo",
    "Returns AI": "IA de Devoluciones",
    "Customs API": "API de Aduanas",
    "Architecture": "Arquitectura",
    "Network Map": "Mapa de Red",
    "Security": "Seguridad",
    "Data Privacy": "Privacidad de Datos",
    "Sustainability": "Sostenibilidad",
    "Contact": "Contacto",
    "Partner Portal": "Portal de Socios",
    "Support": "Soporte",
    "© 2026 Parcellino Swiss. Engineered in Zurich.": "© 2026 Parcellino Swiss. Diseñado en Zúrich.",
    "Terms": "Términos",
    "Privacy": "Privacidad",
    "Our warehouse automation reduces pick-error rates to less than 0.01%, ensuring your customers receive exactly what they ordered, every time.": "Nuestra automatización de almacenes reduce las tasas de errores de recolección a menos del 0.01%, asegurando que tus clientes reciban exactamente lo que ordenaron, en todo momento.",
    "Real-time Inventory Sync": "Sincronización de Inventario en Tiempo Real",
    "Same-day Dispatch (14:00 cutoff)": "Despacho en el Mismo Día (corte a las 14:00)",
    "Custom Brand Packaging": "Embalaje de Marca Personalizado",
    "Fragile Item Specialists": "Especialistas en Artículos Frágiles",
    "Luxury requires a different standard of care. We treat every parcel as a masterpiece, with dedicated white-glove inspection zones.": "El lujo requiere un estándar diferente de cuidado. Tratamos cada paquete como una obra maestra, con zonas de inspección dedicadas de guante blanco.",
    "Enhanced Security Vaults": "Bóvedas de Seguridad Mejoradas",
    "Climate Controlled Storage": "Almacenamiento con Control de Clima",
    "Premium Tissue & Wax Seal handling": "Manejo Premium de Papel Seda y Sello de Cera",
    "Serial Number Tracking": "Rastreo de Número de Serie",
    "Precision is non-negotiable in medical logistics. Our facility meets the highest Swiss standards for pharmaceutical storage.": "La precisión no es negociable en la logística médica. Nuestra instalación cumple con los más altos estándares suizos para el almacenamiento farmacéutico.",
    "GDP Compliant Handling": "Manejo Conforme a BPD",
    "Cold Chain Logistics": "Logística de Cadena de Frío",
    "Batch & Expiry Management": "Batch & Expiry Management",
    "Sterile Environment Options": "Opciones de Entorno Estéril",
    "Returns are the second point of customer contact. We process returns in under 24 hours to ensure rapid restocking or liquidation.": "Las devoluciones son el segundo punto de contacto con el cliente. Procesamos devoluciones en menos de 24 horas para garantizar reposición o liquidación rápida.",
    "Photo-Verified Inspections": "Inspecciones Verificadas por Foto",
    "Quality Grading System": "Sistema de Clasificación de Calidad",
    "Rapid Customer Refunds": "Reembolsos Rápidos al Cliente",
    "Regional Consolidation": "Consolidación Regional",
    "Cross-border trade shouldn't be a bottleneck. Our in-house customs experts ensure 100% compliance with EU and Swiss regulations.": "El comercio transfronterizo no debería ser un cuello de botella. Nuestros expertos aduaneros internos garantizan un cumplimiento del 100% con las normativas de la UE y de Suiza.",
    "IOSS & OSS Management": "IOSS & OSS Management",
    "HS Code Classification": "Clasificación de Códigos HS",
    "Duty & Tax Calculation": "Cálculo de Aranceles e Impuestos",
    "Frictionless EU-Swiss corridor": "Corredor UE-Suiza sin fricciones",
    "E-Com Management": "E-Com Management",
    "Engineered efficiency.": "Eficiencia diseñada.",
    "Meticulous storage in our single, highly secure Swiss facility. Optimized storage space custom-tailored for early-stage brands.": "Almacenamiento meticuloso en nuestra única instalación suiza de alta seguridad. Espacio de almacenamiento optimizado a medida para marcas en etapa inicial.",
    "See How We Work": "Mira Cómo Trabajamos",
    "See Process": "Ver Proceso",
    "Swiss Warehousing": "Almacenamiento Suizo",
    "View Storage": "Ver Almacenamiento",
    "We manually handle and process your Shopify, WooCommerce, and Amazon orders with Swiss precision. Perfect for emerging brands looking for error-free execution and personal care without complex setups.": "Manejamos y procesamos manualmente tus pedidos de Shopify, WooCommerce y Amazon con precisión suiza. Perfecto para marcas emergentes que buscan ejecución sin errores y cuidado personal sin configuraciones complejas.",
    "© 2026 Precision Fulfillment": "© 2026 Fulfillment de Precisión",
    "We deliver more than products. We provide trust, efficiency and growth.": "Entregamos más que productos. Brindamos confianza, eficiencia y crecimiento.",
    "100% Biodegradable Boxes": "Cajas 100% Biodegradables",
    "60-Minute Picking Window": "Ventana de Recolección de 60 Minutos",
    "Carbon-Balanced Operations": "Operaciones Balanceadas en Carbono",
    "Climate-Controlled Space": "Espacio con Control de Clima",
    "Condition Grading Audit": "Auditoría de Clasificación de Condiciones",
    "Custom Tailored Shelving": "Estanterías Hechas a Medida",
    "Deliver unforgettable premium unboxing moments with high-grade, sustainable materials certified for maximum shipping protection.": "Ofrece momentos de unboxing premium inolvidables con materiales sostenibles de alta calidad, certificados para la máxima protección en el envío.",
    "Eco-Certified Fillers": "Rellenos Eco-Certificados",
    "Ensure immediate product validation and rapid restocking to maintain inventory liquidity and customer satisfaction.": "Garantiza validación inmediata del producto y reposición rápida para mantener la liquidez del inventario y la satisfacción del cliente.",
    "Express Dispatch Services": "Servicios de Envío Exprés",
    "High-Priority Scheduling": "Programación de Alta Prioridad",
    "High-Security Protocols": "Protocolos de Alta Seguridad",
    "Instant Return Restocking": "Reposición Instantánea de Devoluciones",
    "Manual Quality Audit": "Auditoría de Calidad Manual",
    "Our swift picking processes move with synchronized precision, minimizing transit delays and expediting shipping times.": "Nuestros rápidos procesos de recolección se mueven con precisión sincronizada, minimizando retrasos en el tránsito y agilizando los tiempos de envío.",
    "Personalized Client Dashboard": "Panel de Control de Cliente Personalizado",
    "Premium Custom Branding": "Marca Personalizada Premium",
    "Shopify & WooCommerce Integration": "Integración con Shopify y WooCommerce",
    "Single Secure Swiss Facility": "Única Instalación Segura en Suiza",
    "Swift Customer Status Updates": "Rápidas Actualizaciones de Estado del Cliente",
    "Verification & Inspection": "Verificación e Inspección",
    "We process orders with absolute white-glove manual precision, ensuring 100% accuracy and customized attention for emerging brands.": "Procesamos pedidos con absoluta precisión manual de guante blanco, garantizando un 100% de exactitud y atención personalizada para marcas emergentes.",
    "Your inventory is protected within our single state-of-the-art secure Swiss facility with optimized shelving and strict climate control.": "Tu inventario está protegido dentro de nuestra única instalación suiza segura de última generación con estanterías optimizadas y estricto control de clima.",
    "Zero Pick-Error Tolerance": "Tolerancia Cero a Errores de Recolección",
    "Zero-Setup Complexities": "Cero Complejidades de Configuración",
    "Swiss Ambition": "Ambición Suiza",
    "Our company was established by a ": "Nuestra empresa fue fundada por una ",
    "woman entrepreneur": "mujer emprendedora",
    " who has seen and felt the pain in the fulfillment process, and we have a ": " que ha visto y sentido el dolor en el proceso de fulfillment, y tenemos una ",
    "simple vision": "visión simple",
    " to make fulfillment ": " para hacer que el fulfillment sea ",
    "seamless, reliable and exceptional": "fluido, confiable y excepcional",
    "Smart logistics, proactive service and uncompromising attention to detail": "Logística inteligente, servicio proactivo y atención intransigente al detalle",
    ", all for the purpose of ensuring that the quality of our service is reflected in every order you place.": ", todo con el propósito de asegurar que la calidad de nuestro servicio se refleje en cada pedido que realices.",
    "We deliver more than products.": "Entregamos más que productos.",
    "We provide trust, efficiency and growth.": "Proporcionamos confianza, eficiencia y crecimiento.",
    "WhatsApp": "WhatsApp",
    "Pioneering Swiss fulfillment and E-commerce logistics Switzerland solutions. From the heart of the nation, we provide real-time logistics and the Swiss standard of reliability.": "Soluciones pioneras en fulfillment suizo y logística de comercio electrónico en Suiza. Desde el corazón de la nación, proporcionamos logística en tiempo real y el estándar suizo de fiabilidad.",
    "Premier Shopify fulfillment Switzerland services. We manually handle and process your Shopify, WooCommerce, and Amazon orders with Swiss precision, offering error-free care without complexities.": "Servicios premier de fulfillment para Shopify en Suiza. Manejamos y procesamos manualmente tus pedidos de Shopify, WooCommerce y Amazon con precisión suiza, ofreciendo atención sin errores ni complejidades.",
    "Leading provider of fulfillment Switzerland services and precision architecture.": "Proveedor líder de servicios de fulfillment en Suiza y arquitectura de precisión.",
    "Nationwide": "Nacional",
    "Client Success": "Éxito del Cliente",
    "Trusted by Industry Leaders": "Confiado por Líderes de la Industria",
    "We have been working with Parcellino in IT/logistics for our brand Hydrux for some time now... The cooperation is efficient, reliable, and absolutely professional.": "Llevamos un tiempo trabajando con Parcellino en TI/logística para nuestra marca Hydrux... La cooperación es eficiente, fiable y absolutamente profesional.",
    "Parcellino takes over our fulfillment and we at dirts benefit from the fast processing... Parcellino is the perfect partner.": "Parcellino se hace cargo de nuestro fulfillment y en dirts nos beneficiamos de un procesamiento rápido... Parcellino es el socio perfecto.",
    "By outsourcing our warehouse and fulfillment, we benefited on our core competencies while being sure this part is handled professionally.": "Al externalizar nuestro almacén y fulfillment, nos enfocamos en nuestras competencias básicas con la seguridad de que esta parte se gestiona profesionalmente.",
    "Founder": "Fundador",
    "Swiss Precision Warehouse": "Almacén de Precisión Suizo",
    "Swiss Logistics Network": "Red Logística Suiza",
    "Toggle Theme": "Cambiar Tema"
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [currentLang, setCurrentLang] = useState('Deutsch');

  useEffect(() => {
    const savedLang = localStorage.getItem('parcellino-lang');
    if (savedLang) {
      setCurrentLang(savedLang);
    }
  }, []);

  const setLanguage = (lang) => {
    setCurrentLang(lang);
    localStorage.setItem('parcellino-lang', lang);
  };

  const t = (text) => {
    if (currentLang === 'English') return text;
    return translations[currentLang]?.[text] || text;
  };

  const tRich = (text) => {
    const translated = t(text);
    if (typeof translated !== 'string') return translated;
    const parts = translated.split(/(parcellino)/i);
    if (parts.length === 1) return translated;
    return parts.map((part, index) => 
      part.toLowerCase() === 'parcellino' 
        ? <span key={index} className="text-swiss-red lowercase">parcellino</span> 
        : part
    );
  };

  return (
    <LanguageContext.Provider value={{ currentLang, setLanguage, t, tRich }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
